### ISSUE TITLE
404 for style.css when running via IntelliJ IDEA run config and not via Gradle

### ISSUE THREAD

**Issue by joshaustintech** [rife2/rife2-hello#11]
Could be doing something wrong, but when I run this locally style.css returns 404 Not Found. I'm too tired right now to solve this, but opening an issue to remind myself later unless anybody else wants to take this on.

**Comment by joshaustintech** [comment]
Screenshot:

<img width="677" alt="Screenshot 2023-03-06 at 10 03 51 PM" src="https://user-images.githubusercontent.com/83935880/223317927-5e3932e3-4c9d-4282-aa95-e0e57a8ec221.png">

**Comment by gbevin** [comment]
Is your repo clean and unmodified? I just downloaded a clean checkout, did "./gradlew run", used a browser with a clean cache and the stylesheet is found correctly.

**Comment by joshaustintech** [comment]
Pulled in a clean and unmodified copy and still had the issue. However, I ran it via IntelliJ and not `./gradlew run`.  When I use `./gradlew run` in the command line the issue is gone. Updating the title to be more specific.

**Comment by gbevin** [comment]
Yes that is known, because IDEA runs from a different current directory when simply pressing the play buttons. You can edit the launch parameters and set the current directory to the project directory, then it works fine.

**Comment by gbevin** [comment]
This is fixed with the RIFE2 build system
